[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm install --include=dev --cache /tmp/.npm --no-audit --no-fund && npm run build && php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache"
